### ISSUE TITLE
pubDate issue

### ISSUE THREAD

**Issue by magnett** [JRG-Developer/MediaRSSParser#1]
Hi!
First of all, thanks for this awesome piece of work!
I had a weird issue. I was parsing an rss feed using the simulator and everything worked fine. Then i run the code on the device and saw that the pub dates where nil!
I thought that it had to do with internasiolatization since my device languge is set to Greek and i was right.

By setting the locale at "RSSParser.h", the issue was fixed:
- (void)setUpDateFormatter
  {
  self.dateFormatter = [[NSDateFormatter alloc] init];
  self.dateFormatter.locale=[[NSLocale alloc] initWithLocaleIdentifier:@"gr_GR"];
  [self.dateFormatter setDateFormat:@"EEE, dd MMM yyyy HH:mm:ss Z"];
  }

**Comment by JRG-Developer** [comment]
Instead of setting
<code>
self.dateFormatter.locale=[[NSLocale alloc] initWithLocaleIdentifier:@"gr_GR"];
</code>

Does this work?
<code>
self.dateFormatter.locale = [NSLocale currentLocale];
</code>

This still passes all unit tests. If this works for you, I'm happy to make this change and push a new pod spec version to trunk.

**Comment by magnett** [comment]
@JRG-Developer 
The first thing i tried was the currentLocale and strangely it didn't work. You can replicate this issue in simulator too if you set the language to Greek and try to parse for example this feed: http://www.taxheaven.gr/exports/mobiledata/mobile_news_section_1.xml

**Comment by JRG-Developer** [comment]
As a workaround,

`dateFormatter` is a public property on `RSSParser`, so you can set whatever `locale` you'd like on it directly.

Other than this, I'm not sure of a great fix for it.

If you figure something out, feel free to submit a pull request. Otherwise, I'm closing this issue for now.
